esphome:
  name: esp32dev1
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_ssid

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

uart:
  tx_pin: GPIO15
  rx_pin: GPIO2
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"

switch:
  - platform: gpio
    pin: 
      number: GPIO4
    id: pms_enable
    name: "Enable sensor"
  
interval:
  - interval: 120s
    then:
      - switch.turn_on: pms_enable
      - delay: 6s
      - switch.turn_off: pms_enable