esphome:
  name: esp32dev1
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_ssid

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

sensor:
  - platform: adc
    name: "Temperature"
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    icon: "mdi:temperature-celsius"
    accuracy_decimals: 1
    pin: GPIO34
    update_interval: 60s
    filters:
      - offset: -0.5
      - multiply: 100
    
